# EndpointCalls/function_map.py

from . import (
    get_EquipmentE360_business_units,
    get_EquipmentE360_fuel_costs,
    get_EquipmentE360_work_order_costs,
    get_EquipmentE360_work_order_details,
    get_EquipmentE360_custom_fields,
    get_EquipmentE360_custom_field_categories,
    get_HeavyBidEstimates_business_units,
    get_HeavyBidEstimates_partitions,
    get_HeavyJob_business_units,
    get_HeavyJob_jobs,
    get_HeavyJob_jobcosts,
    get_HeavyJob_costcodes,
    get_HeavyJob_jobemployees,
    get_HeavyJob_jobequipment,
    get_HeavyJob_jobmaterials,
    get_HeavyJob_materials,
    get_HeavyJob_timecards,
    get_HeavyJob_diaries,
    get_HeavyJob_employees,
    get_HeavyJob_equipment_types,
    get_HeavyJob_equipment,
    get_HeavyJob_equipmenthours,
    get_HeavyJob_employeehours,
    get_Safety_incidents,
    get_Safety_meetings,
    get_Setups_accounting_templates,
    get_Setups_business_units,
    get_Setups_jobs,
    get_Setups_equipment,
    get_Setups_employees,
    get_Skills_skills,
    get_Skills_employeeskills,
    get_Telematics_equipment,
    get_token,
    get_Users_business_units,
    get_Users_jobs,
    get_Users_roles,
    get_Users_subscription_groups,
    get_Users_users,
)

FUNCTION_MAP = {
    'get_EquipmentE360_business_units': get_EquipmentE360_business_units,
    'get_EquipmentE360_fuel_costs': get_EquipmentE360_fuel_costs,
    'get_EquipmentE360_work_order_costs': get_EquipmentE360_work_order_costs,
    'get_EquipmentE360_work_order_details': get_EquipmentE360_work_order_details,
    'get_EquipmentE360_custom_fields': get_EquipmentE360_custom_fields,
    'get_EquipmentE360_custom_field_categories': get_EquipmentE360_custom_field_categories,
    'get_HeavyBidEstimates_business_units': get_HeavyBidEstimates_business_units,
    'get_HeavyBidEstimates_partitions': get_HeavyBidEstimates_partitions,
    'get_HeavyJob_business_units': get_HeavyJob_business_units,
    'get_HeavyJob_jobs': get_HeavyJob_jobs,
    'get_HeavyJob_jobcosts': get_HeavyJob_jobcosts,
    'get_HeavyJob_costcodes': get_HeavyJob_costcodes,
    'get_HeavyJob_jobemployees': get_HeavyJob_jobemployees,
    'get_HeavyJob_jobequipment': get_HeavyJob_jobequipment,
    'get_HeavyJob_jobmaterials': get_HeavyJob_jobmaterials,
    'get_HeavyJob_materials': get_HeavyJob_materials,
    'get_HeavyJob_timecards': get_HeavyJob_timecards,
    'get_HeavyJob_diaries': get_HeavyJob_diaries,
    'get_HeavyJob_employees': get_HeavyJob_employees,
    'get_HeavyJob_equipment_types': get_HeavyJob_equipment_types,
    'get_HeavyJob_equipment': get_HeavyJob_equipment,
    'get_HeavyJob_equipmenthours': get_HeavyJob_equipmenthours,
    'get_HeavyJob_employeehours': get_HeavyJob_employeehours,
    'get_Safety_incidents': get_Safety_incidents,
    'get_Safety_meetings': get_Safety_meetings,
    'get_Setups_accounting_templates': get_Setups_accounting_templates,
    'get_Setups_business_units': get_Setups_business_units,
    'get_Setups_jobs': get_Setups_jobs,
    'get_Setups_equipment': get_Setups_equipment,
    'get_Setups_employees': get_Setups_employees,
    'get_Skills_skills': get_Skills_skills,
    'get_Skills_employeeskills': get_Skills_employeeskills,
    'get_Telematics_equipment': get_Telematics_equipment,
    'get_token': get_token,
    'get_Users_business_units': get_Users_business_units,
    'get_Users_jobs': get_Users_jobs,
    'get_Users_roles': get_Users_roles,
    'get_Users_subscription_groups': get_Users_subscription_groups,
    'get_Users_users': get_Users_users,
}
