name: Daily Run

on:
  schedule:
    - cron: '45 13 * * *'  # This runs at 9:45 AM Eastern Time (UTC-4/5)
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Upgrade to v3

      - name: Set up Python
        uses: actions/setup-python@v4  # Upgrade to v4
        with:
          python-version: '3.10'  # Specify your Python version

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Install Google Chrome
        run: |
          # Update package list
          echo "Updating package list..."
          sudo apt-get update

          # Install Google Chrome
          echo "Installing Google Chrome..."
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb

          # Clean up
          rm google-chrome-stable_current_amd64.deb

          # Verify Chrome installation
          google-chrome --version
          
      - name: Install ChromeDriver
        run: |
          # Get the installed Chrome version
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+' | head -1 | cut -d '.' -f 1-3)

          echo "Installed Chrome version: $CHROME_VERSION"

          # Fetch the matching ChromeDriver version
          echo "Fetching the latest ChromeDriver for version $CHROME_VERSION"
          CHROME_DRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")

          # Fallback if specific version is not found
          if [ -z "$CHROME_DRIVER_VERSION" ]; then
            echo "Specific ChromeDriver version for $CHROME_VERSION not found. Using the latest stable version."
            CHROME_DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          fi

          echo "Installing ChromeDriver version: $CHROME_DRIVER_VERSION"

          # Download and install ChromeDriver
          wget -N "https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

          # Clean up
          rm chromedriver_linux64.zip

          # Verify ChromeDriver installation
          chromedriver --version

        env:
          HCSS_USERNAME: ${{ secrets.HCSS_USERNAME }}
          HCSS_PASSWORD: ${{ secrets.HCSS_PASSWORD }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          TARGET_EMAIL: ${{ secrets.TARGET_EMAIL }}

      - name: Run main.py
        run: python main.py
        env:
          HCSS_USERNAME: ${{ secrets.HCSS_USERNAME }}
          HCSS_PASSWORD: ${{ secrets.HCSS_PASSWORD }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
   
